### PR TITLE
Use python3 in the debian package

### PR DESCRIPTION
**Pull request by asottile**
See #18

### CODE REVIEW

**Comment by asottile** [comment]
Stupid lucid with python3.1.  I guess I'll hack around that (internally at yelp `python3` deb points to `python3.5`)

**Comment by asottile** [comment]
And precise and wheezy :/

@chriskuehl do we need to keep supporting wheezy and precise?

**Comment by chriskuehl** [comment]
nope i think we can kill them

**Comment by asottile** [comment]
Cool, I'll keep lucid for for yelp's sake -- one day we'll be able to drop that :/

**Pull request merged**
